-- 095_belt_promotion_sent_for_recheck.sql
--
-- FEATURE: expand belt_promotion_requests.status so the "Notify
-- Trainer" flow can flip the request into a new intermediate state
-- instead of hard-declining it.
--
-- Old status set : pending | approved | declined
-- New status set : pending | approved | declined | sent_for_recheck | closed
--
--   • sent_for_recheck — institution sent the request back to the
--     trainer for a second look. Trainer curriculum row goes back to
--     "Promote Belt" so they can submit a fresh request; institution
--     UI still shows the row (labelled "Sent for Recheck") so the
--     admin has a record of what they did.
--
--   • closed — a prior sent_for_recheck / declined row that has been
--     superseded by a fresh 'pending' submission from the trainer.
--     Kept for audit only; hidden from every consumer surface.
--
-- Idempotent: the CHECK constraint's autogenerated name is discovered
-- and dropped before the new constraint is added, so re-running the
-- migration on an already-updated DB is a no-op.

BEGIN;

DO $$
DECLARE
  ck_name TEXT;
BEGIN
  -- Find the existing CHECK constraint on the status column so we
  -- can drop it by its autogenerated name (varies per environment).
  SELECT conname INTO ck_name
    FROM pg_constraint
   WHERE conrelid = 'belt_promotion_requests'::regclass
     AND contype  = 'c'
     AND pg_get_constraintdef(oid) ILIKE '%status%';

  IF ck_name IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE belt_promotion_requests DROP CONSTRAINT %I',
      ck_name
    );
  END IF;

  -- Fresh CHECK with the two new states appended. Named explicitly
  -- so future migrations can reference it deterministically.
  ALTER TABLE belt_promotion_requests
    ADD CONSTRAINT belt_promotion_requests_status_check
    CHECK (status IN (
      'pending',
      'approved',
      'declined',
      'sent_for_recheck',
      'closed'
    ));
END $$;

COMMIT;
