// src/pages/RefundCancellationPolicy.jsx
//
// Public route: /refund-cancellation-policy
//
// Play-Store-compliant refund & cancellation policy for Veerify.
// Covers institution subscriptions (paid by academies), student
// enrolment fees (paid to academies), event fees, and Razorpay
// dispute flows.
//
// Same shared header / footer / helpers as PrivacyPolicy.jsx so the
// six legal pages read as one consistent document set.

import React, { useEffect } from 'react';
import VeerifyHeader from './VeerifyHeader';
import VeerifyFooter from './VeerifyFooter';

const LAST_UPDATED = '19 July 2026';

export default function RefundCancellationPolicy() {
  useEffect(() => {
    document.title = 'Refund & Cancellation Policy — Veerify';
    setMeta(
      'description',
      'Veerify refund and cancellation rules for institution subscriptions, student course enrolments, event fees, and Razorpay-processed payments.',
    );
  }, []);

  return (
    <div style={styles.page}>
      <VeerifyHeader
        title="Refund & Cancellation Policy"
        subtitle="How cancellations, refunds, and disputes are handled on Veerify."
      />

      <main style={styles.main}>
        <p style={styles.meta}>
          <strong>Last updated:</strong> {LAST_UPDATED}
        </p>

        <p style={styles.lead}>
          This policy describes when and how you can cancel a subscription
          or a course enrolment on Veerify, and the circumstances under
          which a refund may be issued. It applies to every payment
          processed through the Veerify mobile app or the web dashboard at{' '}
          <a href="https://veerifyapp.com" style={styles.link}>veerifyapp.com</a>.
          It is incorporated into our{' '}
          <a href="/terms-and-conditions" style={styles.link}>Terms &amp; Conditions</a>{' '}
          by reference.
        </p>

        <Section title="1. Payment Types Covered">
          <p>Veerify processes three distinct payment types. Each has its own refund rules:</p>
          <ul style={styles.ul}>
            <li><strong>Institution subscription</strong> — an academy pays Veerify to use the platform (Monthly, Quarterly, Half-Yearly, or Annual plans).</li>
            <li><strong>Student course enrolment fee</strong> — a student pays the <em>academy</em> for course access, collected via a Razorpay Payment Link generated by Veerify.</li>
            <li><strong>Event registration fee</strong> — a student or trainer pays an academy for admission to an academy-hosted event.</li>
          </ul>
          <p>
            All payments are processed by <strong>Razorpay Software Pvt Ltd</strong>. Veerify never sees or stores card, UPI, or bank credentials.
          </p>
        </Section>

        <Section title="2. Institution Subscriptions">
          <h3 style={styles.h3}>2.1 Cancellation</h3>
          <ul style={styles.ul}>
            <li>Institution subscriptions do <strong>not auto-renew</strong>. A subscription automatically ends on its renewal date if you do not make a fresh payment. There is nothing to cancel — simply let the plan expire.</li>
            <li>Within the last 7 days of a subscription, a "Renew Now" button appears on the admin dashboard. Ignoring it lets the subscription lapse at the natural end.</li>
            <li>After the renewal date, the account enters a grace period defined by the plan. After grace, feature access is locked until you renew.</li>
          </ul>

          <h3 style={styles.h3}>2.2 Refunds</h3>
          <ul style={styles.ul}>
            <li><strong>Free trial</strong> — no payment is charged during the trial period. Nothing to refund.</li>
            <li><strong>Within 7 days of a first-ever paid subscription</strong> — if the platform is not fit for your academy, contact us within 7 days of your first payment and we will refund the amount in full, minus any Razorpay processing fees which Razorpay does not return to us.</li>
            <li><strong>After 7 days</strong> — subscription fees are non-refundable. You may continue using the platform through the end of the paid term.</li>
            <li><strong>Renewals</strong> — subsequent renewal payments are non-refundable because you have already been using the platform.</li>
            <li><strong>Upgrades / downgrades</strong> — the price difference is prorated for the remaining term. Upgrades are charged immediately; downgrades take effect at the next renewal.</li>
          </ul>

          <h3 style={styles.h3}>2.3 Termination by Veerify</h3>
          <p>
            If we terminate your subscription for a violation of our <a href="/terms-and-conditions" style={styles.link}>Terms &amp; Conditions</a>, no refund is due. If we terminate for any reason outside your control (e.g. discontinuation of the Service), we will refund the unused pro-rated portion of the current term.
          </p>
        </Section>

        <Section title="3. Student Course Enrolment Fees">
          <p>
            When a student pays a course fee through Veerify, the money goes to the enrolling academy, not to Veerify. Veerify acts as a technology intermediary and payment aggregator (via Razorpay).
          </p>

          <h3 style={styles.h3}>3.1 Cancellation by the student</h3>
          <ul style={styles.ul}>
            <li>You may leave an enrolment at any time by contacting your academy directly. The academy will update your enrolment status.</li>
            <li>Whether a refund is due, and how much, is determined by the <strong>academy's own refund policy</strong>. Different academies have different cancellation windows, no-show rules, and pro-rata refund schedules.</li>
            <li>If your academy has not published a refund policy, please ask them for one in writing before paying.</li>
          </ul>

          <h3 style={styles.h3}>3.2 Cancellation by the academy</h3>
          <ul style={styles.ul}>
            <li>If the academy cancels the course or a batch you have paid for, the academy is responsible for refunding your fee.</li>
            <li>Veerify will assist in facilitating the refund on request but is not liable for the amount itself.</li>
          </ul>

          <h3 style={styles.h3}>3.3 Failed / disputed payments</h3>
          <ul style={styles.ul}>
            <li>If a Razorpay payment fails or is cancelled mid-checkout, no money is charged and no refund is required. Your enrolment stays in <em>Pending Payment</em> status; you can retry any time via the Pay Now button.</li>
            <li>If your card is charged but Veerify shows the enrolment as pending for more than <strong>24 hours</strong>, contact <a href="mailto:support@veerifyapp.com" style={styles.link}>support@veerifyapp.com</a> with your payment reference id. We will reconcile with Razorpay and either activate the enrolment or refund the charge.</li>
            <li>Chargebacks initiated with your bank without first contacting us or the academy may result in immediate suspension of your account pending investigation.</li>
          </ul>
        </Section>

        <Section title="4. Event Registration Fees">
          <ul style={styles.ul}>
            <li>Event fees are set by the hosting academy and paid to the academy through Veerify.</li>
            <li>Refunds for cancelled events are the responsibility of the hosting academy.</li>
            <li>If an event is cancelled by the academy, request a refund from them directly. Veerify will facilitate on request.</li>
            <li>No-show / late-arrival refunds are at the academy's discretion.</li>
          </ul>
        </Section>

        <Section title="5. How to Request a Refund">
          <p>To request a refund that falls within the eligibility rules above:</p>
          <ol style={styles.ol}>
            <li>Email <a href="mailto:support@veerifyapp.com" style={styles.link}>support@veerifyapp.com</a> from the email address registered on your account.</li>
            <li>Include your payment reference id (visible on the invoice PDF you received by email, or on the Payment History screen in the app).</li>
            <li>Describe the reason for the request.</li>
          </ol>
          <p>
            We acknowledge every refund request within <strong>2 business days</strong> and issue a decision within <strong>7 business days</strong>. Approved refunds are processed back to the original payment method via Razorpay and typically reflect on your statement within <strong>5–10 business days</strong>, depending on your bank.
          </p>
        </Section>

        <Section title="6. Non-Refundable Items">
          <ul style={styles.ul}>
            <li>Razorpay processing fees on any payment that Razorpay does not refund to us.</li>
            <li>Any add-on services or one-time charges that have been fully delivered.</li>
            <li>Subscription fees paid more than 7 days ago, unless we terminate the Service.</li>
            <li>Fees paid by cash, UPI, bank transfer, or cheque directly to the academy (these are outside Veerify's payment gateway and are handled between you and the academy).</li>
          </ul>
        </Section>

        <Section title="7. Chargebacks">
          <p>
            If you dispute a charge with your bank or card network without first contacting us or the academy, we may:
          </p>
          <ul style={styles.ul}>
            <li>Suspend your account until the dispute is resolved.</li>
            <li>Provide the payment gateway with our records of the transaction, including your account activity, in defence of the charge.</li>
            <li>Refuse future service if the dispute is not upheld in your favour.</li>
          </ul>
          <p>Please always contact us first — we can usually resolve issues faster than a chargeback.</p>
        </Section>

        <Section title="8. Currency &amp; Taxes">
          <ul style={styles.ul}>
            <li>All prices on Veerify are in <strong>Indian Rupees (INR)</strong>.</li>
            <li>Prices are inclusive of applicable taxes unless stated otherwise.</li>
            <li>GST invoices are generated automatically for every successful payment and emailed to your registered address.</li>
          </ul>
        </Section>

        <Section title="9. Changes to This Policy">
          <p>
            We may amend this policy from time to time. Material changes will be notified in-app and by email at least 7 days before they take effect. The "Last updated" date at the top of this page reflects the current version.
          </p>
        </Section>

        <Section title="10. Contact">
          <p>For any refund or cancellation question:</p>
          <div style={styles.contactBox}>
            <p style={{ margin: 0 }}><strong>Veerify — Billing Support</strong></p>
            <p style={{ margin: '4px 0' }}>
              Email:{' '}
              <a href="mailto:support@veerifyapp.com" style={styles.link}>support@veerifyapp.com</a>
            </p>
            <p style={{ margin: '4px 0' }}>
              Response time: within 2 business days.
            </p>
          </div>
        </Section>
      </main>

      <VeerifyFooter lastUpdated={LAST_UPDATED} />
    </div>
  );
}

// ─── Helpers ──────────────────────────────────────────────────────
function Section({ title, children }) {
  return (
    <section style={styles.section}>
      <h2 style={styles.h2}>{title}</h2>
      {children}
    </section>
  );
}

function setMeta(name, content) {
  if (typeof document === 'undefined') return;
  let tag = document.querySelector(`meta[name="${name}"]`);
  if (!tag) {
    tag = document.createElement('meta');
    tag.setAttribute('name', name);
    document.head.appendChild(tag);
  }
  tag.setAttribute('content', content);
}

// ─── Styles ───────────────────────────────────────────────────────
const BRAND = '#E63946';
const TEXT  = '#111827';
const MUTED = '#4B5563';
const BG    = '#FFFFFF';

const styles = {
  page: {
    minHeight: '100vh',
    background: BG,
    color: TEXT,
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    lineHeight: 1.6,
  },
  main: { maxWidth: 820, margin: '0 auto', padding: '32px 20px 64px' },
  meta:  { color: MUTED, fontSize: 13, margin: '0 0 20px' },
  lead:  { fontSize: 16, color: TEXT, marginBottom: 28 },
  section: { marginTop: 36 },
  h2: {
    fontSize: 22, fontWeight: 800, color: TEXT,
    borderBottom: `2px solid ${BRAND}`,
    display: 'inline-block', paddingBottom: 4,
    marginTop: 0, marginBottom: 14,
  },
  h3: {
    fontSize: 15, fontWeight: 800, color: TEXT,
    marginTop: 18, marginBottom: 8,
  },
  ul: { paddingLeft: 22, margin: '0 0 12px', color: MUTED, fontSize: 15 },
  ol: { paddingLeft: 22, margin: '0 0 12px', color: MUTED, fontSize: 15 },
  link: { color: BRAND, textDecoration: 'none', fontWeight: 700 },
  contactBox: {
    marginTop: 8,
    padding: 16,
    background: '#FFF5F6',
    borderLeft: `4px solid ${BRAND}`,
    borderRadius: 8,
    fontSize: 14,
  },
};
